We have been given the optimization problem
Maximize Z = 6x_1 + 8x_2  <br>
subject to the boundary conditions : <br>
 1x_1 + 1x_2 <= 10 <br>
 2x_1 + 3x_2 <= 25 <br>
 1x_1 + 5x_2 <= 35 <br>

In [1]:
n = 2
m = 3

In [2]:
import numpy as np

In [14]:
C_j = np.array([6,8,0,0,0])
a_ij = np.array([[1,1,1,0,0],[2,3,0,1,0],[1,5,0,0,1]])
X_B = np.array([10,25,35])
B = np.eye(3)
C_b = np.array([0,0,0])
B_inv = np.linalg.inv(B)
y = np.dot(C_b,B_inv)
bv = np.array([2,3,4])
nbv = np.array([0,1])
print('The basic variables are : ' + str(bv+1) )
print('With the coefficients C_b : ' + str(C_b))
print('And X_B = ' + str(X_B) )
print('The non-basic variables are : '+ str(nbv + 1))
print('B : \n'+str(B))
print('B^{-1} : \n' + str(B_inv))
print('y = C_b.B^{-1} = ' + str(y))

The basic variables are : [3 4 5]
With the coefficients C_b : [0 0 0]
And X_B = [10 25 35]
The non-basic variables are : [1 2]
B : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
B^{-1} : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
y = C_b.B^{-1} = [0. 0. 0.]


In [15]:
id1 =0
nbcid = 0
max = 0
for i in range(2):
    print('P' + str(nbv[i] + 1) + ' = '+ str(a_ij[:,nbv[i]]))
    print('Now, C' + str(nbv[i] + 1) + ' - Z' + str(nbv[i] + 1) + ' = C' + str(nbv[i] + 1) + ' - yP' + str(nbv[i] + 1) )
    print('=' + str(  C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]] ) ) ))
    if (C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )) > max :
        max = C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )
        id1 = nbv[i]
        nbcid = i
print('\nThe maximum value of Cj - Zj is :' + str(max) )
print('\nSo the entering variable is ' + str(id1+1) + ' ' + str(nbcid))

P1 = [1 2 1]
Now, C1 - Z1 = C1 - yP1
=6.0
P2 = [1 3 5]
Now, C2 - Z2 = C2 - yP2
=8.0

The maximum value of Cj - Zj is :8.0

So the entering variable is 2 1


In [16]:
    print('Now, Pbar_j = B^{-1} Pj = ' + str( np.dot(B_inv,  a_ij[:,id1])) )
    print('So, we divide X_B by Pbar_j to get')
    print(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1])))
    id2 = np.argmin(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1])))
    minim = np.min(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1]))) 
    print('Here the minimum value of the matrix is ' + str(minim) )
    print('So, the leaving variable is ' + str(bv[id2]+1))
    nbv[nbcid] = bv[id2]
    bv[id2] = id1
    X_B = (X_B) - minim*np.dot(B_inv,  a_ij[:,id1])
    X_B[id2] = minim
    C_b[id2] = C_j[bv[id2]]
    B[:,id2] = a_ij[:,id1]
    B_inv = np.linalg.inv(B)
    y = np.dot(C_b,B_inv)
    print('The basic variables are : ' + str(bv+1) )
    print('With the coefficients C_b : ' + str(C_b))
    print('And X_B = ' + str(X_B) )
    print('The non-basic variables are : '+ str(nbv + 1))
    print('B : \n'+str(B))
    print('B^{-1} : \n' + str(B_inv))
    print('y = C_b.B^{-1} = ' + str(y))

Now, Pbar_j = B^{-1} Pj = [1. 3. 5.]
So, we divide X_B by Pbar_j to get
[10.          8.33333333  7.        ]
Here the minimum value of the matrix is 7.0
So, the leaving variable is 5
The basic variables are : [3 4 2]
With the coefficients C_b : [0 0 8]
And X_B = [3. 4. 7.]
The non-basic variables are : [1 5]
B : 
[[1. 0. 1.]
 [0. 1. 3.]
 [0. 0. 5.]]
B^{-1} : 
[[ 1.   0.  -0.2]
 [ 0.   1.  -0.6]
 [ 0.   0.   0.2]]
y = C_b.B^{-1} = [0.  0.  1.6]


In [17]:
    id1 =0
    nbcid = 0
    max = 0
    for i in range(2):
        print('P' + str(nbv[i] + 1) + ' = '+ str(a_ij[:,nbv[i]]))
        print('Now, C' + str(nbv[i] + 1) + ' - Z' + str(nbv[i] + 1) + ' = C' + str(nbv[i] + 1) + ' - yP' + str(nbv[i] + 1) )
        print('=' + str(  C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]] ) ) ))
        if (C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )) > max :
            max = C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )
            id1 = nbv[i]
            nbcid = i
    print('\nThe maximum value of Cj - Zj is :' + str(max) )
    print('\nSo the entering variable is ' + str(id1+1) )

P1 = [1 2 1]
Now, C1 - Z1 = C1 - yP1
=4.4
P5 = [0 0 1]
Now, C5 - Z5 = C5 - yP5
=-1.6

The maximum value of Cj - Zj is :4.4

So the entering variable is 1 0


In [8]:
id1

0

In [9]:
max

4.4

In [18]:
print('Now, Pbar_j = B^{-1} Pj = ' + str( np.dot(B_inv,  a_ij[:,id1])) )
print('So, we divide X_B by Pbar_j to get')
print(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1])))
id2 = np.argmin(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1])))
minim = np.min(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1]))) 
print('Here the minimum value of the matrix is ' + str(minim) )
print('So, the leaving variable is ' + str(bv[id2]+1))
nbv[nbcid] = bv[id2]
bv[id2] = id1
X_B = (X_B) - minim*np.dot(B_inv,  a_ij[:,id1])
X_B[id2] = minim
C_b[id2] = C_j[bv[id2]]
B[:,id2] = a_ij[:,id1]
B_inv = np.linalg.inv(B)
y = np.dot(C_b,B_inv)
print('The basic variables are : ' + str(bv+1) )
print('With the coefficients C_b : ' + str(C_b))
print('And X_B = ' + str(X_B) )
print('The non-basic variables are : '+ str(nbv + 1))
print('B : \n'+str(B))
print('B^{-1} : \n' + str(B_inv))
print('y = C_b.B^{-1} = ' + str(y))

Now, Pbar_j = B^{-1} Pj = [0.8 1.4 0.2]
So, we divide X_B by Pbar_j to get
[ 3.75        2.85714286 35.        ]
Here the minimum value of the matrix is 2.857142857142857
So, the leaving variable is 4
The basic variables are : [3 1 2]
With the coefficients C_b : [0 6 8]
And X_B = [0.71428571 2.85714286 6.42857143]
The non-basic variables are : [4 5]
B : 
[[1. 1. 1.]
 [0. 2. 3.]
 [0. 1. 5.]]
B^{-1} : 
[[ 1.         -0.57142857  0.14285714]
 [ 0.          0.71428571 -0.42857143]
 [ 0.         -0.14285714  0.28571429]]
y = C_b.B^{-1} = [ 0.          3.14285714 -0.28571429]


In [19]:
id1 =0
nbcid = 0
max = 0
for i in range(2):
    print('P' + str(nbv[i] + 1) + ' = '+ str(a_ij[:,nbv[i]]))
    print('Now, C' + str(nbv[i] + 1) + ' - Z' + str(nbv[i] + 1) + ' = C' + str(nbv[i] + 1) + ' - yP' + str(nbv[i] + 1) )
    print('=' + str(  C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]] ) ) ))
    if (C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )) > max :
        max = C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )
        id1 = nbv[i]
        nbcid = i
print('\nThe maximum value of Cj - Zj is :' + str(max) )
print('\nSo the entering variable is ' + str(id1) + ' ' + str(nbcid))

P4 = [0 1 0]
Now, C4 - Z4 = C4 - yP4
=-3.142857142857143
P5 = [0 0 1]
Now, C5 - Z5 = C5 - yP5
=0.2857142857142856

The maximum value of Cj - Zj is :0.2857142857142856

So the entering variable is 4 1


In [20]:
print('Now, Pbar_j = B^{-1} Pj = ' + str( np.dot(B_inv,  a_ij[:,id1])) )
print('So, we divide X_B by Pbar_j to get')
print(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1])))
id2 = np.argmin(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1])))
minim = np.min(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1]))) 
print('Here the minimum value of the matrix is ' + str(minim) )
print('So, the leaving variable is ' + str(bv[id2]+1))
nbv[nbcid] = bv[id2]
bv[id2] = id1
X_B = (X_B) - minim*np.dot(B_inv,  a_ij[:,id1])
X_B[id2] = minim
C_b[id2] = C_j[bv[id2]]
B[:,id2] = a_ij[:,id1]
B_inv = np.linalg.inv(B)
y = np.dot(C_b,B_inv)
print('The basic variables are : ' + str(bv+1) )
print('With the coefficients C_b : ' + str(C_b))
print('And X_B = ' + str(X_B) )
print('The non-basic variables are : '+ str(nbv + 1))
print('B : \n'+str(B))
print('B^{-1} : \n' + str(B_inv))
print('y = C_b.B^{-1} = ' + str(y))

Now, Pbar_j = B^{-1} Pj = [ 0.14285714 -0.42857143  0.28571429]
So, we divide X_B by Pbar_j to get
[ 5.         -6.66666667 22.5       ]
Here the minimum value of the matrix is -6.666666666666667
So, the leaving variable is 1
The basic variables are : [3 5 2]
With the coefficients C_b : [0 0 8]
And X_B = [ 1.66666667 -6.66666667  8.33333333]
The non-basic variables are : [4 1]
B : 
[[1. 0. 1.]
 [0. 0. 3.]
 [0. 1. 5.]]
B^{-1} : 
[[ 1.         -0.33333333  0.        ]
 [ 0.         -1.66666667  1.        ]
 [ 0.          0.33333333  0.        ]]
y = C_b.B^{-1} = [0.         2.66666667 0.        ]


In [21]:
id1 =0
nbcid = 0
max = 0
for i in range(2):
    print('P' + str(nbv[i] + 1) + ' = '+ str(a_ij[:,nbv[i]]))
    print('Now, C' + str(nbv[i] + 1) + ' - Z' + str(nbv[i] + 1) + ' = C' + str(nbv[i] + 1) + ' - yP' + str(nbv[i] + 1) )
    print('=' + str(  C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]] ) ) ))
    if (C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )) > max :
        max = C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )
        id1 = nbv[i]
        nbcid = i
print('\nThe maximum value of Cj - Zj is :' + str(max) )
print('\nSo the entering variable is ' + str(id1) + ' ' + str(nbcid))

P4 = [0 1 0]
Now, C4 - Z4 = C4 - yP4
=-2.6666666666666665
P1 = [1 2 1]
Now, C1 - Z1 = C1 - yP1
=0.666666666666667

The maximum value of Cj - Zj is :0.666666666666667

So the entering variable is 0 1


In [33]:
C_j = np.array([1,2,3,0,0])
a_ij = np.array([[1,5,6,0,0],[1,3,2,0,1]])
X_B = np.array([30,18])
B = np.eye(2)
C_b = np.array([0,0])
B_inv = np.linalg.inv(B)
y = np.dot(C_b,B_inv)
bv = np.array([3,4])
nbv = np.array([0,1,2])
print('The basic variables are : ' + str(bv+1) )
print('With the coefficients C_b : ' + str(C_b))
print('And X_B = ' + str(X_B) )
print('The non-basic variables are : '+ str(nbv + 1))
print('B : \n'+str(B))
print('B^{-1} : \n' + str(B_inv))
print('y = C_b.B^{-1} = ' + str(y))

The basic variables are : [4 5]
With the coefficients C_b : [0 0]
And X_B = [30 18]
The non-basic variables are : [1 2 3]
B : 
[[1. 0.]
 [0. 1.]]
B^{-1} : 
[[1. 0.]
 [0. 1.]]
y = C_b.B^{-1} = [0. 0.]


In [34]:
id1 =0
nbcid = 0
max = 0
for i in range(3):
    print('P' + str(nbv[i] + 1) + ' = '+ str(a_ij[:,nbv[i]]))
    print('Now, C' + str(nbv[i] + 1) + ' - Z' + str(nbv[i] + 1) + ' = C' + str(nbv[i] + 1) + ' - yP' + str(nbv[i] + 1) )
    print('=' + str(  C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]] ) ) ))
    if (C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )) > max :
        max = C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )
        id1 = nbv[i]
        nbcid = i
print('\nThe maximum value of Cj - Zj is :' + str(max) )
print('\nSo the entering variable is ' + str(id1+1) + ' ' + str(nbcid))

P1 = [1 1]
Now, C1 - Z1 = C1 - yP1
=1.0
P2 = [5 3]
Now, C2 - Z2 = C2 - yP2
=2.0
P3 = [6 2]
Now, C3 - Z3 = C3 - yP3
=3.0

The maximum value of Cj - Zj is :3.0

So the entering variable is 3 2


In [28]:
print('Now, Pbar_j = B^{-1} Pj = ' + str( np.dot(B_inv,  a_ij[:,id1])) )
print('So, we divide X_B by Pbar_j to get')
print(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1])))
id2 = np.argmin(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1])))
minim = np.min(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1]))) 
print('Here the minimum value of the matrix is ' + str(minim) )
print('So, the leaving variable is ' + str(bv[id2]+1))
nbv[nbcid] = bv[id2]
bv[id2] = id1
X_B = (X_B) - minim*np.dot(B_inv,  a_ij[:,id1])
X_B[id2] = minim
C_b[id2] = C_j[bv[id2]]
B[:,id2] = a_ij[:,id1]
B_inv = np.linalg.inv(B)
y = np.dot(C_b,B_inv)
print('The basic variables are : ' + str(bv+1) )
print('With the coefficients C_b : ' + str(C_b))
print('And X_B = ' + str(X_B) )
print('The non-basic variables are : '+ str(nbv + 1))
print('B : \n'+str(B))
print('B^{-1} : \n' + str(B_inv))
print('y = C_b.B^{-1} = ' + str(y))

Now, Pbar_j = B^{-1} Pj = [6. 2.]
So, we divide X_B by Pbar_j to get
[5. 9.]
Here the minimum value of the matrix is 5.0
So, the leaving variable is 4
The basic variables are : [3 5]
With the coefficients C_b : [3 0]
And X_B = [5. 8.]
The non-basic variables are : [1 2 4]
B : 
[[6. 0.]
 [2. 1.]]
B^{-1} : 
[[ 0.16666667  0.        ]
 [-0.33333333  1.        ]]
y = C_b.B^{-1} = [0.5 0. ]


In [29]:
id1 =0
nbcid = 0
max = 0
for i in range(3):
    print('P' + str(nbv[i] + 1) + ' = '+ str(a_ij[:,nbv[i]]))
    print('Now, C' + str(nbv[i] + 1) + ' - Z' + str(nbv[i] + 1) + ' = C' + str(nbv[i] + 1) + ' - yP' + str(nbv[i] + 1) )
    print('=' + str(  C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]] ) ) ))
    if (C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )) > max :
        max = C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )
        id1 = nbv[i]
        nbcid = i
print('\nThe maximum value of Cj - Zj is :' + str(max) )
print('\nSo the entering variable is ' + str(id1+1) + ' ' + str(nbcid))

P1 = [1 1]
Now, C1 - Z1 = C1 - yP1
=0.5
P2 = [5 3]
Now, C2 - Z2 = C2 - yP2
=-0.5
P4 = [0 0]
Now, C4 - Z4 = C4 - yP4
=0.0

The maximum value of Cj - Zj is :0.5

So the entering variable is 1 0


In [30]:
print('Now, Pbar_j = B^{-1} Pj = ' + str( np.dot(B_inv,  a_ij[:,id1])) )
print('So, we divide X_B by Pbar_j to get')
print(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1])))
id2 = np.argmin(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1])))
minim = np.min(np.divide(X_B,np.dot(B_inv,  a_ij[:,id1]))) 
print('Here the minimum value of the matrix is ' + str(minim) )
print('So, the leaving variable is ' + str(bv[id2]+1))
nbv[nbcid] = bv[id2]
bv[id2] = id1
X_B = (X_B) - minim*np.dot(B_inv,  a_ij[:,id1])
X_B[id2] = minim
C_b[id2] = C_j[bv[id2]]
B[:,id2] = a_ij[:,id1]
B_inv = np.linalg.inv(B)
y = np.dot(C_b,B_inv)
print('The basic variables are : ' + str(bv+1) )
print('With the coefficients C_b : ' + str(C_b))
print('And X_B = ' + str(X_B) )
print('The non-basic variables are : '+ str(nbv + 1))
print('B : \n'+str(B))
print('B^{-1} : \n' + str(B_inv))
print('y = C_b.B^{-1} = ' + str(y))
id1 =0
nbcid = 0
max = 0
for i in range(3):
    print('P' + str(nbv[i] + 1) + ' = '+ str(a_ij[:,nbv[i]]))
    print('Now, C' + str(nbv[i] + 1) + ' - Z' + str(nbv[i] + 1) + ' = C' + str(nbv[i] + 1) + ' - yP' + str(nbv[i] + 1) )
    print('=' + str(  C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]] ) ) ))
    if (C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )) > max :
        max = C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )
        id1 = nbv[i]
        nbcid = i
print('\nThe maximum value of Cj - Zj is :' + str(max) )
print('\nSo the entering variable is ' + str(id1+1) + ' ' + str(nbcid))

Now, Pbar_j = B^{-1} Pj = [0.16666667 0.66666667]
So, we divide X_B by Pbar_j to get
[30. 12.]
Here the minimum value of the matrix is 11.999999999999998
So, the leaving variable is 5
The basic variables are : [3 1]
With the coefficients C_b : [3 1]
And X_B = [ 3. 12.]
The non-basic variables are : [5 2 4]
B : 
[[6. 1.]
 [2. 1.]]
B^{-1} : 
[[ 0.25 -0.25]
 [-0.5   1.5 ]]
y = C_b.B^{-1} = [0.25 0.75]


In [31]:
id1 =0
nbcid = 0
max = 0
for i in range(3):
    print('P' + str(nbv[i] + 1) + ' = '+ str(a_ij[:,nbv[i]]))
    print('Now, C' + str(nbv[i] + 1) + ' - Z' + str(nbv[i] + 1) + ' = C' + str(nbv[i] + 1) + ' - yP' + str(nbv[i] + 1) )
    print('=' + str(  C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]] ) ) ))
    if (C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )) > max :
        max = C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )
        id1 = nbv[i]
        nbcid = i
print('\nThe maximum value of Cj - Zj is :' + str(max) )
print('\nSo the entering variable is ' + str(id1+1) + ' ' + str(nbcid))

P5 = [0 1]
Now, C5 - Z5 = C5 - yP5
=-0.75
P2 = [5 3]
Now, C2 - Z2 = C2 - yP2
=-1.5000000000000004
P4 = [0 0]
Now, C4 - Z4 = C4 - yP4
=0.0

The maximum value of Cj - Zj is :0

So the entering variable is 1 0


In [177]:
B

array([[1., 0., 1.],
       [0., 1., 3.],
       [0., 0., 5.]])

In [179]:
y

array([0. , 0. , 1.6])

In [180]:
for i in range(n):
    print('P' + str(nbv[i] + 1) + ' = '+ str(a_ij[:,nbv[i]]))
    print('Now, C' + str(nbv[i] + 1) + ' - Z' + str(nbv[i] + 1) + ' = C' + str(nbv[i] + 1) + ' - yP' + str(nbv[i] + 1) )
    print('=' + str(  C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]] ) ) ))
    if (C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )) > max :
        max = C_j[nbv[i]] - np.dot(y, np.transpose(a_ij[:,nbv[i]]) )
        id1 = nbv[i]
        nbcid = i
print('\nThe maximum value of Cj - Zj is :' + str(max) )
print('\nSo the entering variable is ' + str(id1+1) )
check = 1
iterations = 0

4.4
0.0
